# Generated by Django 3.1.6 on 2022-05-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0005_auto_20220503_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(verbose_name=''),
        ),
    ]
